const DOMAIN_DESCRIPTIONS: Record<string, string> = {
	pk_id: "Auto-generated numeric primary key for a table.",
	uuid_v7: "Time-ordered UUID for globally unique identifiers.",
	foreign_key: "Identifier that references a row in another table.",
	integer: "Whole numbers without a fractional part.",
	unsigned_integer: "Non-negative whole numbers and numeric identifiers.",
	bigint: "Whole numbers that may exceed the regular integer range.",
	real: "Approximate numbers with a fractional part.",
	numeric: "Exact general-purpose numeric values.",
	decimal: "Exact fixed-precision values such as prices or measurements.",
	float: "Approximate fractional values with standard precision.",
	double: "Approximate fractional values with higher precision.",
	varchar: "Variable-length text with a practical length limit.",
	char: "Fixed-length text such as a one-character code.",
	binary: "Fixed-size raw binary data.",
	blob: "Arbitrary binary data such as compact files or hashes.",
	longtext: "Very large plain-text content.",
	date: "ISO calendar date without a time component.",
	datetime: "Combined date and time without timestamp behavior.",
	json: "Structured JSON stored in a database-native form where available.",
	first_name: "A person's given or first name.",
	last_name: "A person's family or last name.",
	full_name: "A complete personal or display name.",
	username: "A short account handle used for identification or login.",
	short_description: "A concise description suitable for lists and summaries.",
	long_description: "A detailed plain-text description.",
	short_text: "A short free-form text value.",
	text: "General-purpose plain text.",
	markdown: "Rich text authored and stored as Markdown.",
	slug: "URL-safe identifier derived from a title or name.",
	url: "A full external or website link.",
	amount: "A monetary amount using the project's canonical storage format.",
	currency_code: "ISO currency code such as EUR or USD.",
	percentage: "An exact percentage or ratio value.",
	timestamp: "UTC date and time used for recorded events.",
	days: "Duration or count measured in days.",
	months: "Duration or count measured in months.",
	years: "Duration or count measured in years.",
	hours: "Duration or count measured in hours.",
	minutes: "Duration or count measured in minutes.",
	boolean: "True or false state, commonly used for is_ or has_ fields.",
	email: "Email address with enough room for standard addresses.",
	phone_number: "International phone number, normally in E.164 form.",
	locale: "BCP-47 language/region tag such as en-US.",
	code_short: "Very short machine-readable code.",
	code: "Medium-length machine-readable code.",
	code_long: "Long machine-readable code or external identifier.",
	status_enum: "Named workflow or state-machine status.",
	sku: "Product or inventory stock-keeping unit.",
	gtin: "Global Trade Item Number - EAN/UPC barcode identifier.",
	tax_id: "VAT or company tax identifier.",
	street_line_1: "Primary street address line.",
	street_line_2: "Optional secondary address information.",
	city: "City or locality name.",
	state_province: "State, province, or regional subdivision.",
	postal_code: "Postal or ZIP code.",
	country_code: "ISO country code.",
	country_name: "Full country display name.",
	password_hash: "Secure password hash in a standard encoded format.",
	ip_address: "IPv4 or IPv6 address stored as text.",
	json_data: "Serialized structured application data.",
	image_path: "Path or URL pointing to an image asset.",
	file_path: "Path or URL pointing to a document or other file.",
	quantity: "An order or inventory quantity, whole or fractional (e.g. 2 pcs, 0.5 liter).",
};

export function get_domain_description(domain_name: string): string {
	return DOMAIN_DESCRIPTIONS[domain_name] ?? "Predefined database type for this column.";
}
