import { db } from "$config/db";
import { timed_query } from "$lib/timed_sql";
import { ARCHIVE_SCOPE_ALL, ARCHIVE_SCOPE_ARCHIVED, ARCHIVE_SCOPE_LIVE } from "$config/db_structure";
import { archive_clause, archive_counts_query, to_archive_counts, type ArchiveCounts, type ArchiveFilter } from "$lib/archive";

// db.unsafe() - legacy manual CRUD. Uses dynamic ORDER BY, offset-based pagination, and
// scope_clause injection. Regex-validated sort_field.

export interface Record {
	id: number;
	module_code: string;
	feature_name: string;
	table_name: string;
	scope_key: string;
	display_name: string;
	where_clause: string;
	sort_order: number;
	is_default: number;
	archived_at?: string | null;
	archived_by_user_id?: number | null;
}

export interface Options {
	option_value: number | string;
	option_text: string;
}

export type GlobalScopeListFilter = "user" | "all";

/** The admin list defaults to user-authored business filters. */
export function resolve_global_scope_list_filter(value: string): GlobalScopeListFilter {
	return value === "all" ? "all" : "user";
}

export async function get_all_records(): Promise<Record[]> {
	try {
		return await timed_query("global_scopes", "get_all_records", async () => {
			const _records = await db`SELECT * FROM global_scopes WHERE archived_at IS NULL ORDER BY id ASC`;
			const records = _records;

			return records as Record[];
		});
	} catch (error) {
		console.error("Error fetching all records:", error);
		return [];
	}
}

export async function get_global_scopes_select_options(): Promise<Options[]> {
	try {
		return await timed_query("global_scopes", "get_select_options", async () => {
			const records = await db`SELECT id as option_value, table_name as option_text FROM global_scopes WHERE archived_at IS NULL ORDER BY table_name ASC LIMIT 50`;
			return records as Options[];
		});
	} catch (error) {
		console.error("Error fetching select options:", error);
		return [];
	}
}

export async function get_record_by_id(id: number, include_archived: boolean = false): Promise<Record | undefined> {
	try {
		return await timed_query("global_scopes", "get_record_by_id", async () => {
			const archive_where = include_archived ? "" : " AND archived_at IS NULL";
			const by_id_query = `SELECT * FROM global_scopes WHERE id = ?${archive_where} LIMIT 1`;
			const records = (await db.unsafe(by_id_query, [id])) as Record[];
			const record = records[0];
			return record as Record | undefined;
		});
	} catch (error) {
		console.error("Error fetching record by id:", error);
		return undefined;
	}
}

export async function search_records(
	search: string = "",
	offset: number = 0,
	limit: number = 20,
	order_by: string = "id::asc",
	scope_clause: string = "",
	filter_clauses: { clause: string; params: any[]; }[] = [],
	archive_filter: ArchiveFilter = "live",
	list_filter: GlobalScopeListFilter = "user",
): Promise<{ records: Record[]; total: number; }> {
	try {
		const parts = order_by.split("::");
		const sort_field = parts[0] || "id";
		const sort_direction = parts[1] || "asc";
		const valid_direction = ["asc", "desc"].includes(sort_direction?.toLowerCase() || "") ? sort_direction.toLowerCase() : "asc";

		if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(sort_field)) {
			return search_records(search, offset, limit, "id::asc", scope_clause, filter_clauses, archive_filter, list_filter);
		}

		return await timed_query("global_scopes", "search_records", async () => {
			let records: Record[] = [];
			let total: number = 0;

			const where_clauses: string[] = [];
			const list_archive_where = archive_clause(archive_filter);
			if (list_archive_where) { where_clauses.push(list_archive_where); }
			const params: any[] = [];

			// Archive scopes are generated by CRUD and are implementation details of
			// each resource. Keep the admin list focused on business filters unless
			// the operator explicitly asks to see every filter.
			if (list_filter === "user") {
				where_clauses.push("scope_key NOT IN (?, ?, ?)");
				params.push(ARCHIVE_SCOPE_LIVE, ARCHIVE_SCOPE_ARCHIVED, ARCHIVE_SCOPE_ALL);
			}

			if (search) {
				const search_term = `%${search}%`;
				where_clauses.push("(scope_key LIKE ? OR display_name LIKE ? OR where_clause LIKE ?)");
				params.push(search_term, search_term, search_term);
			}

			if (scope_clause) { where_clauses.push(`(${scope_clause})`); }

			for (const filter of filter_clauses) {
				where_clauses.push(`(${filter.clause})`);
				params.push(...filter.params);
			}

			const where = where_clauses.length > 0 ? `WHERE ${where_clauses.join(" AND ")}` : "";
			const data_query = `SELECT * FROM global_scopes ${where} ORDER BY ${sort_field} ${valid_direction.toUpperCase()}, id ${valid_direction.toUpperCase()} LIMIT ? OFFSET ?`;
			records = (await db.unsafe(data_query, [...params, limit, offset])) as Record[];

			const count_query = `SELECT COUNT(*) as count FROM global_scopes ${where_clauses.length > 0 ? where : ""}`;
			const count_result = await db.unsafe(count_query, params);
			total = (count_result[0] as any)?.count || 0;

			return { records, total };
		});
	} catch (error) {
		console.error("Error searching records:", error);
		return { records: [], total: 0 };
	}
}
export async function create_record(record: Omit<Record, "id">): Promise<Record> {
	try {
		return await timed_query("global_scopes", "create_record", async () => {
			const insert_result = await db`INSERT INTO global_scopes (module_code, feature_name, table_name, scope_key, display_name, where_clause, sort_order, is_default) VALUES (${record.module_code}, ${record.feature_name || ""}, ${record.table_name}, ${record.scope_key}, ${record.display_name}, ${record.where_clause}, ${record.sort_order}, ${record.is_default})`;
			const get_result = await db`SELECT * FROM global_scopes WHERE id = ${insert_result.lastInsertRowid} LIMIT 1`;
			return get_result[0] as Record;
		});
	} catch (error) {
		console.error("Error creating record:", error);
		throw error;
	}
}

export async function update_record(id: number, record: Omit<Record, "id">): Promise<Record | undefined> {
	try {
		return await timed_query("global_scopes", "update_record", async () => {
			await db`UPDATE global_scopes SET module_code = ${record.module_code}, feature_name = ${record.feature_name || ""}, table_name = ${record.table_name}, scope_key = ${record.scope_key}, display_name = ${record.display_name}, where_clause = ${record.where_clause}, sort_order = ${record.sort_order}, is_default = ${record.is_default} WHERE id = ${id}`;
			const records = await db`SELECT * FROM global_scopes WHERE id = ${id} LIMIT 1`;
			return records[0] as Record | undefined;
		});
	} catch (error) {
		console.error("Error updating record:", error);
		throw error;
	}
}

export async function archive_record(id: number, archived_by_user_id: number | null): Promise<boolean> {
	try {
		return await timed_query("global_scopes", "archive_record", async () => {
			const result = await db`UPDATE global_scopes SET archived_at = CURRENT_TIMESTAMP, archived_by_user_id = ${archived_by_user_id} WHERE id = ${id} AND archived_at IS NULL`;
			return (result.affectedRows ?? result.count ?? result.changes ?? 0) > 0;
		});
	} catch (error) {
		console.error("Error archiving record:", error);
		const error_msg = error instanceof Error ? error.message : String(error);
		if (error_msg.includes("foreign key")) { throw error; }
		return false;
	}
}

export async function restore_record(id: number): Promise<boolean> {
	try {
		return await timed_query("global_scopes", "restore_record", async () => {
			const result = await db`UPDATE global_scopes SET archived_at = NULL, archived_by_user_id = NULL WHERE id = ${id} AND archived_at IS NOT NULL`;
			return (result.affectedRows ?? result.count ?? result.changes ?? 0) > 0;
		});
	} catch (error) {
		console.error("Error restoring record:", error);
		return false;
	}
}

export async function get_archive_counts(scope_clause: string = ""): Promise<ArchiveCounts> {
	try {
		return await timed_query("global_scopes", "get_archive_counts", async () => {
			const counts_query = archive_counts_query("global_scopes", scope_clause);
			const counts_result = await db.unsafe(counts_query, []);
			return to_archive_counts(counts_result[0]);
		});
	} catch (error) {
		console.error("Error fetching archive counts:", error);
		return { total: 0, live: 0, archived: 0 };
	}
}
