import { describe, expect, test } from "bun:test";

// Test the import path construction, import statement, crud entry, and
// spread entry string patterns generated by update_routes_ts().
// These are inline template literals in the source - we test the patterns
// directly so string format changes are caught.

function build_import_path(table_name: string, clean_prefix: string, parent_cli_table: string): string {
	return parent_cli_table ? `${clean_prefix ? `${clean_prefix}/` : ""}${parent_cli_table}/${table_name}` : clean_prefix ? `${clean_prefix}/${table_name}` : table_name;
}

function build_import_stmt(crud_name: string, import_path: string): string { return `import { ${crud_name} } from "$routes/${import_path}";`; }

function build_crud_entry(route_prefix: string, table_name: string, crud_name: string, clean_prefix: string): string {
	const nav_module = clean_prefix ? `, module: "${clean_prefix}"` : "";
	const nav_key = clean_prefix ? `${clean_prefix}.${table_name}` : table_name;
	return `\t{ url: "${route_prefix}/${table_name}", crud: ${crud_name}, nav_title_key: "${nav_key}"${nav_module} },`;
}

function build_spread_entry(crud_name: string): string { return `...${crud_name},`; }

describe("route_registrar - import path construction", () => {
	test("bare table name (no prefix, no parent)", () => expect(build_import_path("users", "", "")).toBe("users"));

	test("table with prefix", () => expect(build_import_path("users", "admin", "")).toBe("admin/users"));

	test("nested table (no prefix, parent)", () => expect(build_import_path("items", "", "equipment")).toBe("equipment/items"));

	test("nested table with prefix", () => expect(build_import_path("items", "system", "equipment")).toBe("system/equipment/items"));
});

describe("route_registrar - import statement", () => {
	test("bare import statement", () => expect(build_import_stmt("users_crud", "users")).toBe("import { users_crud } from \"$routes/users\";"));

	test("prefixed import statement", () => expect(build_import_stmt("admin_users_crud", "admin/users")).toBe("import { admin_users_crud } from \"$routes/admin/users\";"));
});

describe("route_registrar - crud entry", () => {
	test("bare crud entry", () => {
		const entry = build_crud_entry("", "users", "users_crud", "");
		expect(entry).toContain("url: \"/users\"");
		expect(entry).toContain("crud: users_crud");
		expect(entry).toContain("nav_title_key: \"users\"");
		expect(entry).not.toContain("module:");
	});

	test("prefixed crud entry", () => {
		const entry = build_crud_entry("/admin", "users", "admin_users_crud", "admin");
		expect(entry).toContain("url: \"/admin/users\"");
		expect(entry).toContain("crud: admin_users_crud");
		expect(entry).toContain("nav_title_key: \"admin.users\"");
		expect(entry).toContain("module: \"admin\"");
	});

	test("crud entry ends with trailing comma", () => {
		const entry = build_crud_entry("", "users", "users_crud", "");
		expect(entry.endsWith(",")).toBe(true);
	});
});

describe("route_registrar - spread entry", () => test("nested CRUD spread entry", () => expect(build_spread_entry("items_crud")).toBe("...items_crud,")));
